### ISSUE TITLE
Logger writing wrong characters in files

### ISSUE THREAD

**Issue by italo-aurelio** [vtex/toolbelt#1048]
Hi,

I think this is not a crucial issue (maybe this is no a issue at all), but provides a better development experience.

When I run command `vtex logs --all > somefile.log` the logger starts to write inside a file locally, works perfect. But this brings some "formatters" code with wrong characters

```log
...
[32minfo[39m: {
  code: [32m'ERR_HTTP_INVALID_HEADER_VALUE'[39m,
  errorReportMetadata: { errorId: [32m'f5d4c3afd0b915edeaf755825e9fb039'[39m, reportCount: [33m0[39m },
  name: [32m'TypeError'[39m
...
```

Maybe this is something inside this file
https://github.com/vtex/toolbelt/blob/217546e9b021357592911e9364c064a5be89acf5/src/api/logger.ts

I found some similar issue with solutions:
https://stackoverflow.com/questions/34823326/strange-symbols-in-log-with-winston

https://github.com/winstonjs/winston/issues/1416

**Comment by gris** [comment]
Hey @italo-aurelio ! Thank you very much for submitting this issue. It seems like a nice proposed solution indeed. I cannot take a look at this now, next week I will give it a try and investigate it, ok? Thanks again for contributing.

**Comment by gris** [comment]
Actually taking a closer look at the code, it seems that you don't need to redirect the console to a specific file. Since we already send it to ~.vtex/logs. Does that helps? I think there is no code changes in that case, you just need to get the logs file in this folder.

**Comment by italo-aurelio** [comment]
Hi @gris 

Thanks for your attention.

I'm redirecting the logs to a file following this docs: [https://developers.vtex.com/vtex-developer-docs/docs/managing-application-logs#retrieving-application-logs](https://developers.vtex.com/vtex-developer-docs/docs/managing-application-logs#retrieving-application-logs)

I don't know if there are the same logs or if they are produced by toolbelt.
