### ISSUE TITLE
npm install failing for dependencies tree for event-stream@3.3.6

### ISSUE THREAD

**Issue by nekk29** [vtex/toolbelt#1065]
I was trying to add vtex@2.125.1 package with nmp install command but i got an error:

## Expected Behavior
Install the expected version

## Current Behavior
Not installing the expected version, instead I am getting the following error

357 verbose type version
358 verbose stack event-stream: No matching version found for event-stream@3.3.6.
358 verbose stack     at module.exports (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:209:23)
358 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:117:26
358 verbose stack     at async Promise.all (index 9)
358 verbose stack     at async Arborist.[buildDepStep] (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:923:5)
358 verbose stack     at async Arborist.buildIdealTree (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:217:7)
358 verbose stack     at async Promise.all (index 1)
358 verbose stack     at async Arborist.reify (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:134:5)
358 verbose stack     at async Install.install (C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\install.js:137:5)
359 verbose cwd C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-56567fcb
360 verbose Windows_NT 10.0.19042
361 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--force" "--cache=C:\\Users\\User\\AppData\\Local\\npm-cache" "--prefer-offline=false" "--prefer-online=false" "--offline=false" "--no-progress" "--no-save" "--no-audit"
362 verbose node v15.14.0
363 verbose npm  v7.8.0
364 error code ETARGET
365 error notarget No matching version found for event-stream@3.3.6.
366 error notarget In most cases you or one of your dependencies are requesting
366 error notarget a package version that doesn't exist.
367 verbose exit 1

## Possible Solution
Checking the dependencies tree I found that the failing package is event-stream@3.3.6 (https://www.npmjs.com/package/event-stream) which was removed from the npm source, beacuse of this inicident:

https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

The dependency tree for that package is the following:

-> vtex@2.125.1
-> @vtex/api@3.77.0
-> stats-lite@2.2.0
-> npm-run-all@4.1.3
-> ps-tree@1.1.0
-> event-stream@3.3.6

Udating the event-stream package to a higher version could solve the issue

## Steps to Reproduce (for bugs)
Use this package.json file

{
  "version": "1.0.0",
  "name": "sample",
  "description": "Sample",
  "private": true,
  "scripts": {
    "test": "cd ./react && yarn test"
  },
  "devDependencies": {
    "vtex": "^2.121.5"
  }
}

node version: v15.14.0
npm version: 7.8.0

**Comment by gris** [comment]
Hey @nekk29 . I'm not sure what you're trying to achieve. What did you do to get this error? I see that in the steps to reproduce you just put toolbelt as a devDependency. This project is only supposed to be used as a CLI. Please clarify your issue.

**Comment by nekk29** [comment]
Hi @gris, yes I am trying to start an app for vtex, I tried running "npm install vtex" but I got the same error, then I tried to put it directly in the dev dependencies and the error persists. This only happens with npm package manager (the version mentioned in the issue), it does not happen with Yarn, I suppose it is due to the broken reference for the package event-stream@3.3.6

**Comment by gris** [comment]
I'm not sure what do you mean by app. This repo is only a CLI. Besides I wasn't able to reproduce. And I'm not sure how yarn and npm would make a difference regarding dependencies. Yarn registry proxies to npm in the end.
