### ISSUE TITLE
Login redirect fails in WSL

### ISSUE THREAD

**Issue by matheusbronca** [vtex/toolbelt#1101]
## Expected Behavior
After the log-in process, you see a white page saying that everything is going well and you can close the page.

## Current Behavior
Right After the redirect to the local server (In the log-in process), I get an "ERR_CONNECTION_RESET"

## Possible Solution
I've tested the ports and my others applications just run fine, so I think this is some "host" issue.

## Steps to Reproduce (for bugs)
1. type `vtex login {account}` on terminal.
2. choose your gmail account
3. get the error

## Context
I cannot log-in in toolbelt using WSL 2

## Your Environment
Edge Chromium / Chrome / Brave
Windows Version: 10.0.19043 Build 19043
Windows Subsystem for Linux 2: Ubuntu 18.04
NodeJs Version: 14.15.4

https://user-images.githubusercontent.com/61763034/120211290-24081080-c207-11eb-9df3-b665697564ef.mp4

**Comment by matheusbronca** [comment]
I figured out what's happening:

For some reason that I don't know why (probably early versions of Docker Desktop are the culprit) put many port proxies in the windows network.

For those who have a similar issue the workaround is quite simple: 
 

1. Open PowerShell with admin privilege and type in:
`netstat -ano | findstr :3000` => The last right number is probably the IPHelper PID (a network service of windows).

2. Now put `netstat -ano | findstr { PID }` => Replace the brackets expression for the PID number we've discovered in the previous step.

3. All port proxies related to IPHelper will be displayed.

4. Delete all port proxies related to the problem you want to solve. (In this case port: 3000)
`netsh interface portproxy delete v4tov4 listenaddress=0.0.0.0 listenport=3000'
`netsh interface portproxy delete v4tov4 listenaddress=127.0.0.1 listenport=3000'
`netsh interface portproxy delete v4tov4 listenaddress=localhost listenport=3000'

5. Probably everything will be run fine now. 🕊🕊

**Comment by MarlonPassos-git** [comment]
Hi @matheusbronca I'm having the same problem here on WSL2. | I was trying to do your step by step to try to solve it, but when I run this first command ("netstat -ano findstr :3000") in the terminal it doesn't return anything.

Do you know what I can do in this case?

![image](https://user-images.githubusercontent.com/63638196/193469285-96fb8722-6f47-49c9-8e66-630278f8fb7e.png)
