### ISSUE TITLE
"vtex deps diff" is not working anymore after update

### ISSUE THREAD

**Issue by josantana** [vtex/toolbelt#1102]
The last Vtex CLI update broke the `vtex deps diff` command. It is not working as expected anymore.

![Screen Shot 2021-05-31 at 15 46 39](https://user-images.githubusercontent.com/5032844/120231419-c3d59680-c227-11eb-8647-e9dcc6f48d9f.png)

I think the problem is pretty self explanatory.
## Steps to Reproduce (for bugs) 
1. Just run `vtex deps diff master {any-other-workspace}`

**Comment by gris** [comment]
Hey, thanks for opening this issue. I can reproduce this behavior. Would you mind doing a `vtex --version` and print the result here? This will help me on the investigation.

**Comment by josantana** [comment]
So sorry about the late reply. The problem occurs on **2.128.0**. 

I have rolled back to 2.127.0, because I use this feature A LOT to compare workspaces during development.
