### ISSUE TITLE
Error sending files - vtex link

### ISSUE THREAD

**Issue by fernandesmi** [vtex/toolbelt#1107]
## Current Behavior
In the last couple of days I am not able to link the project.
It starts as usual, but stops at a % of files sent and starts again from 0.
![image](https://user-images.githubusercontent.com/51866465/124973612-2594d780-e002-11eb-9a87-7b09218a6ceb.png)
![image](https://user-images.githubusercontent.com/51866465/124973401-dc448800-e001-11eb-97d4-d4d776b2e45c.png)

## Your Environment

-   vtex/2.128.0 linux-x64 node-v10.12.0
-   elementary OS 5.1.7 Hera

**Comment by gris** [comment]
Your project seems big (9mb), our servers have a 60s timeout to complete the requests, if the upload takes more time than that we close the connection. I would recommend trying to reduce the size of your project.

**Comment by AngelRM1** [comment]
What happens with those large projects that are larger, for example 50mb, is there any way to solve this problem?
good day
