### ISSUE TITLE
Fix exiting without deactivating sandbox

### ISSUE THREAD

**Issue by tamorim** [vtex/toolbelt#111]
Maybe exiting with another signal?

**Comment by firstdoit** [comment]
Can you elaborate on this? What's the problem?

**Comment by tamorim** [comment]
@firstdoit I've already fixed that! I'm running some tests before merging.
But, basically, before exiting the toolbelt when running watch we must remove the app from the sandbox (it has a ttl that it's constantly refreshed) so that it's removed instantly.

**Comment by brenoc** [comment]
@tamorim is this related? https://github.com/vtex/toolbelt/issues/70

**Comment by tamorim** [comment]
@brenoc Nope, but I'm working on it as well.

**Comment by tamorim** [comment]
@brenoc Actually is a little bit related haha
