### ISSUE TITLE
Installation doesn't add command vtex- Windows machine

### ISSUE THREAD

**Issue by lucasvschenatto** [vtex/toolbelt#1111]
I was able to install VTEX Toolbelt with yarn and received no errors, but the command `vtex` is not found when I try to run it in the terminal. I also tried to restart the terminal so that it would reload enviroment variables but nothing changed.

## Expected Behavior
I expected the `vtex` command to be available for use.

## Current Behavior
`vtex` command is not found after installing it.

![image](https://user-images.githubusercontent.com/7502124/126852885-386318f5-5b47-4296-9810-60f1c9c59b30.png)

## Your Environment

I installed npm and node.js with nvm as recommended in the npm docs.
I installed nvm with chocolatey.
* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
node.js v16.5.0
npm 7.20.1
yarn 1.22.10
nvm-windows 1.1.7
chocolatey 0.10.15
* Operating System and version (desktop or mobile):
Windows
Edition: Windows 10 Pro
Version: 21H1
SO Compilation: 19043.1110
Experience: Windows Feature Experience Pack 120.2212.3530.0

**Comment by gris** [comment]
Hey Lucas, you might want to try installing toolbelt via this executable https://vtex.io/vtexcli/install/win-x64

**Comment by gris** [comment]
Another thing that might work is adding the vtex command as an env variable. But I recommend going with the installer above

**Comment by lucasvschenatto** [comment]
Thanks for the reply @gris, I actually managed to fix it by coding a .bat file called `vtex` and adding the containing folder to the PATH. Not the best solution but a working hack.

The windows installer seems to be a great option. I think it should be recommended or at least mentioned as an option for Windows users in the READE.md file in this repo.

**Comment by gris** [comment]
For sure! We need to improve a lot documentation. Nice hack.
