### ISSUE TITLE
Handling multiple manifests

### ISSUE THREAD

**Issue by VFabricio** [vtex/toolbelt#1112]
This is a feature request.

I have a use case where I need to keep two environments (one for production, one for QA) in sync. They live in different accounts, but all the code is supposed to be the exactly the same. Therefore, the only difference between them should be the vendor in the manifest.

For such situations, it would be useful to be able to have more than one manifest. I could have, for example, manifest.json and manifest-QA.json files and commit them both to source control. When I wanted to, for example, publish a new version of the app to the QA account, I could override which manifest will be used via a CLI flag (something like `vtex publish -p manifest-QA.json`). Absent this flag, the standard manifest.json would still be used.

If my suggestion is not feasible, or if there is a better way of handling this use case, I would be glad to hear about it.

**Comment by gris** [comment]
You might want to check https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-edition-app
