### ISSUE TITLE
Issue during the vtex login execution

### ISSUE THREAD

**Issue by tiago-freire** [vtex/toolbelt#1129]
$ vtex login xxx
10:31:54.594 - error: Unhandled exception  
10:31:54.597 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
10:31:54.598 - error: post https://vtexid.vtex.com.br/api/vtexid/toolbelt/start?an=xxx  
10:31:54.604 - error: ErrorID: e22c18e40c1ffb7c4a8f6bfbeee3416f

**Comment by SrinivasPeddiBorn** [comment]
> Try doing this:
> 
> * write vtex login
> * When it says, Do you want to use the previous log-in details? write no.
> * write your vtex account and it will do the login process.
> 
> It worked for me.

I am unable to understand please explain details

**Comment by SrinivasPeddiBorn** [comment]
I am unable to understand please explain details
