### ISSUE TITLE
problems with vtex link command

### ISSUE THREAD

**Issue by AngelRM1** [vtex/toolbelt#1136]
Hi friends. I am currently encountering problems when linking projects with a high weight. the counter reaches a certain point and then resets `error: Error receiving project zip file vtex.builder-hub@0.281.1`  (as in the image) and does it many times until it ends with an `error: Unhandled exception`

How could I avoid this problem?
is there any way to increase the connection time with the server?
Is there any other alternative with linking the project avoiding going through the vtex link command in the console?

I hope you can guide me in this problem that does not allow me to work properly. a greeting.

![image](https://user-images.githubusercontent.com/87341281/140589603-ef142989-0b62-4417-a829-543af23bd3b9.png)

![image](https://user-images.githubusercontent.com/87341281/140590404-31736082-3c93-41ea-a81d-21e7d05835c8.png)

**Comment by Giuseppetm** [comment]
This issue is still present.

**Comment by test-jml** [comment]
Alguien ya pudo resolver este problema? ya actualice el toolbelt pero sigue con lo mismo
