### ISSUE TITLE
Error vtex link:  --non-interactive --ignore-engines

### ISSUE THREAD

**Issue by leonleles** [vtex/toolbelt#1148]
![image](https://user-images.githubusercontent.com/34039694/159053043-42b473f2-653f-4e3c-b0c3-d2f5203af5eb.png)

**Comment by GeorgeLR87** [comment]
I have the same problem.

Version 3.8-beta

**Comment by emafriedrichot** [comment]
I suspect this error happens with the last version of yarn https://github.com/yarnpkg/yarn/releases/tag/v1.22.18.

I have installed the version 3.8.1-beta as well @GeorgeLR87, but in my vtex toolbet module path, as dependency I have the 1.22.17 version.

I think as a hotfix, maybe would be a good idea to keep the 1.22.17 version of yarn in package.json.

**Comment by leonleles** [comment]
I solved my problem! The `vtex link` is not very effective with VPN. If using VPN I suggest disabling.
