### ISSUE TITLE
vtex login not workin on WSL

### ISSUE THREAD

**Issue by mvlima** [vtex/toolbelt#1154]
## Current Behavior
When I use VTEX login it says I should update my windows, but my windows is up to date, being last updated 1 hour ago.

![image](https://user-images.githubusercontent.com/51724884/164244761-b7b5f5d2-84ed-4258-bf7d-b38d5995117c.png)

## Your Environment
I'm using:
* Windows 10 v21H2
* WSL Ubuntu 20.04 LTS
* vtex/3.0.0 
* node-v16.14.2

**Comment by MistyKussh** [comment]
How did you solve this?
