### ISSUE TITLE
Skip user prompts on 'vtex release'

### ISSUE THREAD

**Issue by cantoniazzi** [vtex/toolbelt#1155]
Today the `vtex release <type_release> <env_release>` command has some user confirmations at the prompt, which prevents it from being called via script (in CI pipelines for example).

Would it be possible to skip these confirmations or run the command with a force parameter?

Similar to what has already been done for the `vtex publish` command. #714

e.g:
```
vtex release minor beta --yes
```

**Comment by rsbegue** [comment]
Maybe, add for `vtex publish` too.

This is a good issue for me

**Comment by cantoniazzi** [comment]
@rsbegue `printf 'y\n' | vtex publish --yes` works for me.
