### ISSUE TITLE
VTEX LINK ERROR

### ISSUE THREAD

**Issue by Malbathan** [vtex/toolbelt#1161]
19:17:13.479 - error: Unhandled exception  
19:17:13.480 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
19:17:13.480 - error: post https://app.io.vtex.com/vtex.builder-hub/v0/samsungar/zipcodetest/_v/builder/0/link/samsungbr.samsung-store@1.220.0
19:17:37.177 - error: ErrorID: ae7374e340912445632f11915ac5be9c

**Comment by niveditapdixit** [comment]
Facing similar error as mentioned above , Pls help 
11:22:30.982 - error: Unhandled exception
11:22:30.985 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
11:22:30.986 - error: post https://vtexid.vtex.com.br/api/vtexid/toolbelt/start?an=emeapartners
11:22:30.990 - error: ErrorID: cd0921d6047829d5ca30b3e92474a949
