### ISSUE TITLE
vtex link fails after login

### ISSUE THREAD

**Issue by alexm4tos** [vtex/toolbelt#1165]
## Expected Behavior
Should continue linking process after login.

## Current Behavior
After a period with the vtex link active, the login is requested again. However, when completing the login, the program presents a failure that interrupts its operation.

## Possible Solution
Check that the object is not undefined before calling the id (eg. data?.id)

## Steps to Reproduce (for bugs)
1. Stay with the vtex link active for some time without making any changes (I think about 40 minutes).
2. Wait for the login request and do it again.
3. Wait for the welcome message.
4. Error message.

## Your Environment
- vtex/3.0.0 wsl-x64 node-v12.12.0  (Host: windows 11 / Ubuntu as subsystem)

![image](https://user-images.githubusercontent.com/25274156/182458075-fe468e61-b624-4857-a4fc-b75b0c98f156.png)
![image](https://user-images.githubusercontent.com/25274156/182458252-b57fadf7-de9b-4acb-9776-a6b07932476f.png)

**Comment by alexm4tos** [comment]
🆙

**Comment by alexm4tos** [comment]
🆙

**Comment by jacksonadh** [comment]
i have the same problem

**Comment by jacksonadh** [comment]
try `vtex setup`
