### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by caiobbdt** [vtex/toolbelt#1169]
11:53:59.442 - error: Unhandled exception
11:53:59.445 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
11:53:59.448 - error: get https://platform.io.vtex.com/babadotopb2b/caiosworkspace
11:53:59.453 - error: ErrorID: 985e3abb19d2a6d2ce42b8cfcd2206c6

**Comment by ocBruno** [comment]
I am also getting these errors 

12:00:24.303 - error: Unhandled exception  
12:00:24.305 - error: Please report the issue in https://github.com/vtex/toolbelt/issues  
12:00:24.306 - error: get https://infra.io.vtex.com/apps/v0/_account_/_workspace_/apps
12:00:24.309 - error: ErrorID: ea234d14ec5d4e5e23d6b6c7e4bb727e
