### ISSUE TITLE
Can't install vtex cli

### ISSUE THREAD

**Issue by MistyKussh** [vtex/toolbelt#1171]
Getting an error when try to install vtex 

## Expected Behavior
The vtex cli to be installed normally

## Current Behavior
Getting and error with a lib when installing
![image](https://user-images.githubusercontent.com/69552027/189915460-c8663cfb-9765-45b2-97cf-e7c7815ec39f.png)

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment
* Installing vtex 3.0.0
* Operating System and version (desktop or mobile):  wsl ubuntu 20.04/ node 16.15.1
* Link to your project:

**Comment by alexm4tos** [comment]
@MistyKussh you need to [update node](https://nodejs.org/en/) to version 12 or higher. The version of your node, according to the print, is at version 10.19.

**Comment by MistyKussh** [comment]
> @MistyKussh you need to [update node](https://nodejs.org/en/) to version 12 or higher. The version of your node, according to the print, is at version 10.19.

I dont know why I'm getting this message, my node is ate version 16.15

**Comment by alexm4tos** [comment]
try with --ignore-engines in yarn command
`sudo yarn global add vtex@3.0.0 --ignore-engines`
