### ISSUE TITLE
Unhandled exception when vtex login

### ISSUE THREAD

**Issue by rajeshyatirajula** [vtex/toolbelt#1194]
Getting unhandled exception when I do vtex login
error : post https://vtexid.vtex.com.br/api/vtexid/toolbelt/start?an=partnerbcdemo
Error Id : 7b873267f759f0ad8416028bff837fda

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by andreeacalinvtex** [comment]
Hello @rajeshyatirajula what operating system are you using? For me works on Mac, but I have an intern student working on windows and she has the same problem as you. 
Trying to understand why this happens
