### ISSUE TITLE
Unhandled exception: Missing ott on VTEX ID callback call

### ISSUE THREAD

**Issue by Bryceed** [vtex/toolbelt#1212]
I can't link or use another command that depends of an authenticated user, since the callback isn't working anymore

## Current Behavior
Without any clearly reason, I'm unable to login since `127.0.0.1:3000` stopped to callback the login action

## Steps to Reproduce (for bugs)
![image](https://github.com/vtex/toolbelt/assets/42657376/21a0589c-3146-475a-a9e8-e3a925660b4f)
![image](https://github.com/vtex/toolbelt/assets/42657376/436e7c8d-116a-45b3-b693-eadc06128bd2)

## Your Environment

* Version used: 4.0.4
* Environment name and version: [Standalone installer](https://vtex.io/vtexcli/install/win-x64), same issue at any recent browser (Edge, Chrome, Firefox...)
* Operating System and version (desktop or mobile): Windows 11 Enterprise (23H2, build 22631.3155)
* Link to your project: _\~private\~_

**Comment by morant901** [comment]
I have the same problem!

**Comment by miguello-tita** [comment]
I have the same problem!

**Comment by dougl4s-dev** [comment]
I have the same problem!

**Comment by eltonleaopeople** [comment]
Same here

**Comment by thedougdev** [comment]
Guys, I solved this problem by changing the default browser from Google Chrome to Microsoft Edge

**Comment by eltonleaopeople** [comment]
> Guys, I solved this problem by changing the default browser from Google Chrome to Microsoft Edge

Worked with Firefox also, but still annoying that it doesn't work on Chrome :/

**Comment by danielkv** [comment]
I'm having the same problem, using a different browser would not be a solution for me. Someone from @grisvtex to help?

**Comment by andrelcalado** [comment]
Hi, Guys, I solved this problem cleaning every cache and whatever with CCleaner, mainly the browsers data.
On the CCleaner has too a Register section that I recommend yours use to search errors on your computer and fixed it.
Hope that its solve yours problem too.
