### ISSUE TITLE
unable to login in vtex account 

### ISSUE THREAD

**Issue by Amardipsakpal** [vtex/toolbelt#1221]
I am getting error massages Unable to login 
Please report the issue in https://github.com/vtex/toolbelt/issues  
15:08:35.213 - error: post https://vtexid.vtex.com.br/api/vtexid/toolbelt/start?an=xyz  
15:08:35.215 - error: ErrorID: 7f9a193a58afb9888cf80e9b9fae98fa

**Comment by ivanlopezluna** [comment]
The same error here.
![Screenshot_20240417_104738](https://github.com/vtex/toolbelt/assets/23274114/9096fc8e-58dd-4678-9c98-147e56c3e09e)

**Comment by ViggiVi** [comment]
Same issue here, despite login briefly working yesterday night around 12.00am - 1.30 am IST. 

Error ID - 0fd35000d98d78059faeeb9c57f065db

**Comment by miguel2armas** [comment]
Has anyone found a solution?
![Screenshot_269](https://github.com/vtex/toolbelt/assets/57545831/c05021d9-e248-490e-92e3-85e6bf1a1ddd)

**Comment by ivanlopezluna** [comment]
Hi!
Apparently this is related ti a recent ESET update. Try this.
https://forum.eset.com/topic/40702-eset-ssl-protection-produces-an-invalid-certificate-chain-for-nodejs-apps/?do=findComment&comment=183081

**Comment by HarshaClouda** [comment]
![Uploading image.png…]()
