### ISSUE TITLE
I can't use vtex login in any account

### ISSUE THREAD

**Issue by felipelauria** [vtex/toolbelt#1233]
I'm trying to use the simple command vtex login with any VTEX account and I'm receiving an Unhandled exception error.

The expected behavior should be making the login with no problems.

Example:
17:01:44.339 - error: Unhandled exception
17:01:44.342 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
17:01:44.342 - error: post https://vtexid.vtex.com.br/api/vtexid/toolbelt/start?an=mizunobrio
17:01:44.345 - error: ErrorID: 3b814a205e9d25b8e461c265daa8369a

![image](https://github.com/user-attachments/assets/1a0944d9-4a09-4006-8352-6d6d1623b8e0)

I'm using desktop CLI.

**Comment by hellofanny** [comment]
I'm getting the same error :/

**Comment by carolvalenca** [comment]
same error here!

**Comment by mateuspontes** [comment]
@felipelauria which version are you using? It's working for me using 
`vtex/4.0.5 darwin-x64 node-v20.13.1`

Node 20, vtex 4.0.5

**Comment by marcollahc** [comment]
Are you having problems with yarn? If so, check the solution I mentioned in this issue: https://github.com/vtex/toolbelt/issues/1232

**Comment by hellofanny** [comment]
My problem was solved. It was due to an internal setup...

**Comment by Aksharma2799** [comment]
Getting same error

**Comment by Aksharma2799** [comment]
@hellofanny , Can you mention here what need to do ?

**Comment by castillag18** [comment]
@Aksharma2799, Hello, what worked for me was to disable my antivirus and update node.

**Comment by pedrolaxe** [comment]
@felipelauria Check your version of node, I changed to 16.20 and it worked.
