### ISSUE TITLE
Warn on the console if there's a new version

### ISSUE THREAD

**Issue by tamorim** [vtex/toolbelt#127]
Detect the current version and check if there's a new one!
Notify on the console accordingly.

Thanks for the tip, @brenoc :smiley:

**Comment by brenoc** [comment]
How bower implemented it:
https://github.com/wibblymat/bower/commit/258cbe7029914c45d0a7b97d1a47c0becd7af07f

Package: https://github.com/yeoman/update-notifier

**Comment by brenoc** [comment]
They changed to this later:
https://github.com/bower/bower/blob/f4cb047e9df55f03e9971ce4f4341c41d99339e3/lib/bin/bower.js#L136-L145

**Comment by tamorim** [comment]
Closed on 515eb69c6d96d04af1ca2a574baac864669e6b99
