### ISSUE TITLE
Support multiple sandboxes simultaneously on the same terminal

### ISSUE THREAD

**Issue by firstdoit** [vtex/toolbelt#135]
@dfosco

**Comment by tamorim** [comment]
sandbox lol wat is dis

**Comment by firstdoit** [comment]
😂

**Comment by dfosco** [comment]
new number who dis

**Comment by dfosco** [comment]
@tamorim @firstdoit This issue was about being able to run multiple apps/extensions from the same command. To put it in more _modern_ terms:

```sh
vtex link extension-store vtex-tachyons
```
