### ISSUE TITLE
Refactor and reorganize for v1.0.0

### ISSUE THREAD

**Issue by firstdoit** [vtex/toolbelt#137]
- [x] Add proper logging capability with `winston`
- [x] Add parallel testing with `ava`
- [x] Add test coverage with `nyc` and `coveralls`
- [x] Separate services into own (internal) packages
- [x] Convert all async code to Bluebird promises
- [x] Use `inquirer` for prompts
- [x] Use `findhelp` for option parsing
- [x] Use `src/` and `lib/` pattern (from https://github.com/babel/babel)
- [x] Implement `vtex workspace *`
- [x] Implement `vtex install`
- [x] Implement `vtex uninstall`
- [x] Implement `vtex publish`
- [x] Implement `vtex list`
- [x] Implement `vtex login`
- [x] Implement `vtex logout`
- [x] Implement `vtex watch`

**Comment by brenoc** [comment]
I'm developing the services as a separate package.

Is a port of this to node:
https://github.com/vtex/apps-client-net/

**Comment by firstdoit** [comment]
That's perfect!
Em 25 de mai de 2016 17:54, "Breno Calazans" <notifications@github.com>
escreveu:

**Comment by brenoc** [comment]
https://www.npmjs.com/package/@vtex/apps
https://www.npmjs.com/package/@vtex/workspaces

**Comment by firstdoit** [comment]
Wooo! Early Christmas 😁
