### ISSUE TITLE
Show current account and workspace after every command

### ISSUE THREAD

**Issue by firstdoit** [vtex/toolbelt#189]
We should show where each command is being issued without depending on bash support.
## Expected Behavior

The first line of log of every command should be `account/workspace`.
## Current Behavior

The user needs to type `vtex` to find out their account and workspace.
## Context

During the demo it was clear that when juggling multiple workspaces it wasn't easy to keep track of which one you're currently using.

**Comment by tamorim** [comment]
I think that after EVERY command is kinda aggressive, don't you think?

**Comment by firstdoit** [comment]
Most commands, then? 😅

**Comment by rdumont** [comment]
I strongly agree that the first line should **always** tell the account and workspace.

**Comment by tiagonapoli** [comment]
Closed due to inactivity
