### ISSUE TITLE
Voltando aos testes do Storefront

### ISSUE THREAD

**Issue by thiagoalgo** [vtex/toolbelt#191]
Participamos no início do beta do Storefront e estamos querendo retomar. Estou seguindo a documentação, mas não estou conseguindo fazer login com o comando vtex login. Alguém poderia me ajudar dizendo se ainda temos um account habilitado e qual seria? Sou da agencia Avanti e  também precisaria saber se meu usuário (thiago@penseavanti.com.br) continua habilitado

**Comment by tamorim** [comment]
@thiagoalgo Nós ainda não abrimos uma nova etapa de testes. Se você preencheu o formulário que divulgamos anteriormente, avisaremos sobre os testes quando formos abrir uma nova etapa!
Vou fechar essa issue, beleza?
