### ISSUE TITLE
Bypass workspace deletion interaction

### ISSUE THREAD

**Issue by ewilazarus** [vtex/toolbelt#194]
To automate some tasks related to workspace management, it would be great to have the possibility to bypass human interaction by adding a flag to the command `vtex workspace delete {name}`.

## Expected Behavior
```
$ vtex workspace delete {name} -y
info:    Workspace {name} deleted successfully
```

## Current Behavior
```
$ vtex workspace delete {name}
? Are you sure you want to delete workspace {name}? Yes
info:    Workspace {name} deleted successfully
```

## Context
Workspace deletion automation

**Comment by tamorim** [comment]
Done on 12d93b6b14a606b13cb62134f465b5f9dd0e55c1
