### ISSUE TITLE
Allow `vtex publish` to specify optional path to app directory

### ISSUE THREAD

**Issue by ewilazarus** [vtex/toolbelt#202]
Whenever you wish to publish many apps in a row, you have to `cd` into the desired app's directory, and then run the `vtex publish` command. It would be awesome if we could maintain this behavior but also add the possibility to specify the directory you wish to pubish.
## Expected Behavior

``` sh
$ vtex publish path/to/myapp/dir
```

Also, specifying no arguments, it should work as is:

``` sh
$ vtex publish
```

Would be equivalent to:

``` sh
$ vtex publish .
```
## Current Behavior

``` sh
$ cd path/to/myapp/dir
$ vtex publish
```

**Comment by tamorim** [comment]
Done
