### ISSUE TITLE
Notify when Internet connection is bad

### ISSUE THREAD

**Issue by klzns** [vtex/toolbelt#311]
Trying to interacting with Toolbelt with a bad internet connection does not give proper messages.
<img width="568" alt="screen shot 2017-05-26 at 3 40 18 pm" src="https://cloud.githubusercontent.com/assets/284515/26508108/b9d91936-4229-11e7-88eb-06758141883b.png">
<img width="866" alt="screen shot 2017-05-26 at 3 41 31 pm" src="https://cloud.githubusercontent.com/assets/284515/26508127/d3af6dec-4229-11e7-9012-6c2bea241e91.png">

## Expected Behavior
It should hint that the connection is taking too long and sugest that is an Internet connection problem.

## Current Behavior
It feels like the problem is with the VTEX infra.

## Steps to Reproduce (for bugs)
1. Connect to a bad wifi that doesn't work
2. Use any command
3. See the timeout error

## Context
Doing anything.

## Your Environment
* Version used: 2.7.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v7.2.1
* Operating System and version (desktop or mobile): desktop
* Link to your project: n/a

**Comment by tiagonapoli** [comment]
I think this was already solved
