### ISSUE TITLE
Suporte apenas para gallery beta

### ISSUE THREAD

**Issue by HigorCesar** [vtex/toolbelt#33]
O endpoint da gallery está fixo em lib/publish, isso torna dificil testes com a gallery rodando local.

**Comment by tamorim** [comment]
Interessante, eu não sabia que poderia ocorrer de rodar a gallery localmente...
Qual é o seu caso, exatamente?

**Comment by HigorCesar** [comment]
Estou publicando apps no endpoint gallery.vtexlocal.com.br, também estou usando o storefront local. Eu quero fazer testes e entender o funcionamento sem ter que ficar publicando no beta. A galera do linux(vc usa tb né ?) realmente não faz isso, já que não suporta visual studio.

**Comment by tamorim** [comment]
Sim, eu uso também. Já conversei aqui com o @amoreira e ele deu a dica de usar um arquivo de configuração chamado .vtexrc (como existia no toolbelt anterior em C#) que possui configurações de endpoint e application header.
Acredito que isso de ajude, o que acha?

**Comment by HigorCesar** [comment]
O arquivo será por projeto? se for eu acho ok.

**Comment by tamorim** [comment]
Não havíamos pensado por projeto, mas não vejo nenhum impedimento pra isso.
