### ISSUE TITLE
Link runtime dependencies in node_modules folder on initial link

### ISSUE THREAD

**Issue by firstdoit** [vtex/toolbelt#367]
When linking, inspect `manifest.json`, grab the runtime package for each builder, install the dependencies using yarn or npm in a .config folder and finally link them in the corresponding folders. This will allow autocomplete in user's editors without having to manually install e.g. react etc.

**Comment by tiagonapoli** [comment]
This was solved by `@vtex/api`. There wasn't follow-ups on this issue so I'm closing it for cleaning up purposes
