### ISSUE TITLE
Create vtex init

### ISSUE THREAD

**Issue by tamorim** [vtex/toolbelt#39]
Create a new command, called `init` that uses the VTEX generator to generate the structure of an VTEX App project.

**Comment by brenoc** [comment]
The following table maps the Toolbelt command with the generator command.

Toolbelt|generator-vtex
---|---
`vtex init`|`yo vtex`
`vtex init storefront`|`yo vtex:storefront`
`vtex init storefront --simple`|`yo vtex:storefront --simple`
`vtex create component`|`yo vtex:component`

The only thing that I'm not sure yet is about the `create component` command. I don't want the command to be long, at the same time, it's weird for the Toolbelt to create something for the Storefront without a "namespace", like `vtex storefront create component`.

Any suggestion or improvements?

**Comment by tamorim** [comment]
Deprecated
