### ISSUE TITLE
Erro ao fazer re-fresh no browser.

### ISSUE THREAD

**Issue by belchior** [vtex/toolbelt#43]
Watching my-first-app

http://localhost:3000/
webpack result is served from /assets/@alphateam.my-first-app/
content is served from /Users/belchior/www/my-first-app
404s will fallback to /index.html
Version: webpack 1.12.1
Time: 10228ms
chunk    {0} HomePage.js, HomePage.js.map (HomePage) 233 kB {2} [rendered]
chunk    {1} editors/index.js, editors/index.js.map (editors/index) 1.34 kB {2} [rendered]
chunk    {2} common.js, common.js.map (common.js) 261 kB [rendered]
webpack: bundle is now VALID.
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT: no such file or directory, open '/opt/local/lib/node_modules/vtex/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
    at Error (native)

**Comment by tamorim** [comment]
Parece que o tiny-lr (que é uma dependência do toolbelt) está ausente ou algum módulo que ele usa está ausente/com problemas.
A instalação do toolbelt ocorreu ok? Já tentou reinstalar? De repente alguns arquivos foram corrompidos ou ficaram ausentes devido a conexão.

**Comment by belchior** [comment]
O problema estava no meu npm@3.3.x, ele é muito "early adopter". =P na versão 2.x funciona  de boa.

**Comment by tamorim** [comment]
Entendi, deve ser algum problema de peerDependency então.
