### ISSUE TITLE
--server criar servidor express que requer webpack da app

### ISSUE THREAD

**Issue by brenoc** [vtex/toolbelt#44]
O https://github.com/gaearon/react-transform-boilerplate substitui a necessidade do react-hot-loader. Ele agora usa um servidor express com middlewares para rodar o webpack e o react-transform para "hotificar" os componentes.

Para que o Toolbelt rode mais de uma app com hot-load, ele teria que ser o responsavel por rodar o servidor e colocar as novas instancias de webpack de cada app dentro dele.

**Comment by firstdoit** [comment]
https://github.com/glenjamin/webpack-hot-middleware

**Comment by brenoc** [comment]
@firstdoit yep

**Comment by tamorim** [comment]
O server foi adaptado para o novo modelo, mas por questão de prioridade, o hot-reload para múltiplas apps será movido para outra issue para ser feito em um futuro próximo :)
