### ISSUE TITLE
Create an vtex-debug.log file 

### ISSUE THREAD

**Issue by klzns** [vtex/toolbelt#454]
## Current Behavior
Today we need to run `vtex link --verbose` when we want to get the log of errors. This is bad for the user experience, since it shows a lot of messages that the user never reads.

But, if the user runs `vtex link` (no verbose) and an error had occurred, they don't have the log of errors to share with the IO developers.

## Possible Solution
Create a file called `vtex-debug.log` that writes every debug log message necessary for the IO developers to debug the error.

**Comment by tiagonapoli** [comment]
That file was created :rocket:
