### ISSUE TITLE
vtex login travado

### ISSUE THREAD

**Issue by joaomello** [vtex/toolbelt#464]
A toolbelt esta travando no comando `vetex login` no windows, funcionando apenas com a versão v9 do node. No macOS funciona com a versão 11.

## Steps to Reproduce (for bugs)
1. vtex login
2. entre com account
3. faz login no browser
4. console fica travado

Debugando identifiquei que não esta sendo disparado esse evento: https://github.com/vtex/toolbelt/blob/master/src/sse.ts#L108

Não seria uma boa deixar o package.json sempre com a versão direta, sem deixar o range `^`. Para caso uma lib quebre compatibilidade?

Att, Mello.

**Comment by tiagonapoli** [comment]
This was already solved
