### ISSUE TITLE
Decouple webpack from toolbelt

### ISSUE THREAD

**Issue by tamorim** [vtex/toolbelt#52]
Let's discuss!
@rdumont 
@brenoc 
@amoreira

**Comment by brenoc** [comment]
O que acha de criamos um `.toolbeltrc` que teria algo como o `.babelrc`:

Esse é o `.babelrc`:

```json
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}
```

Também teriamos a alternativa de suporte de colocar essas configurações no `package.json`, como no babel: https://babeljs.io/docs/usage/babelrc/

O `.toolbeltrc` seria algo do tipo:

```json
{
  "mode": {
    "default": {
      "runner": "vtex-toolbelt-webpack",
      "options": "server"
    },
    "dev": {
      "runner": "vtex-toolbelt-webpack",
      "options": "webpack"
    }
  }
}
```

Teria um pacote npm chamado "vtex-toolbelt-webpack" que seria o plugin para o Toolbelt rodando o Webpack.

O mode um modo de rodar o mesmo plugin de diferentes formas. Iria rodar o default assim:
```sh
vtex watch breno2
```
Nesse caso ele rodaria o servidor do webpack com hot-load por default.

O outro modo seria uma flag. O nome dos modos poderiam ser predefinidos.
```sh
vtex watch breno2 --dev
```
Nesse caso ele so compilaria os arquivos no webpack, sem servidor e hot-reload.

Também seria possível rodar uma task qualquer definida em um arquivo JS, sem a necessidade de publicar um pacote, como:

```json
{
  "mode": {
    "default": {
      "runner": "./gulp.js"
    }
  }
}
```

**Comment by tamorim** [comment]
@brenoc Me agrada muito essa ideia!
A única coisa sobre a qual fico com dúvida é em relação ao `default

**Comment by brenoc** [comment]
@tamorim discorra! Escreve ai!

**Comment by tamorim** [comment]
@brenoc Acredito que sobrescrever o comportamento padrão não seja uma boa ideia. Em caso de necessidade de usar o comportamento padrão posteriormente, teria um trabalho desnecessário.

Acho que sempre adicionar como uma opção ou comando seja melhor pra integridade do comportamento padrão.

Concorda?

**Comment by brenoc** [comment]
@tamorim não vai sobrescrever o padrão, vai extende-lo. O watch da pasta storefront/ ainda vai funcionar. Isso é uma configuração de como o watch deve rodar, da mesma forma que o babelrc faz.

Pode ser algo como:

```json
{
  "galleryEndPoint": "http://apps.vtexlocal.com.br",
  "plugins": ["vtex-toolbelt-webpack"],
  "options": {
    "vtex-toolbelt-webpack": {
      "server": true
    },
  },
  "env": {
    "development": {
      "plugins": ["vtex-toolbelt-webpack"],
      "options": {
        "vtex-toolbelt-webpack": {
          "server": false
        }
      }
    }
  }
}
```
