### ISSUE TITLE
Update toolbelt to new cookieless Storefront model

### ISSUE THREAD

**Issue by tamorim** [vtex/toolbelt#58]
Let's **kill** the cookie! :hocho:  
Here's the to-do list:

#### `watch`
- [x] We're going to use WebSockets (SignalR) for communication with Storefront when running `watch`
- [x] Specific headers will be passed, containing e-mail, account and the app: `x-vtex-user=<developer-email>`, `x-vtex-account=<account>` and `x-vtex-app=<vendor>.<app-name>`
- `watch` will no longer need a sandbox name, instead it will use an optional argument that will indicate the Workspace which the developer environment will be mirrored (#62)
- [x] Provide a URL for sharing the developer environment. It will follow like this: `<store-url>/?workspace=sb_<developer-email>`
- [x] Check if a workspace of the format `sb_<developer-email>` exists, if not, create it

#### `login`
- [x] The `login` will need an argument, this argument is the account of the store
- [x] Keep the account name somewhere
- [x] Can only be logged on 1 account at a time

**Comment by brenoc** [comment]
> Check if a workspace of the format sb_developer_email exists, if not, create it
@amoreira @tamorim I think Toolbelt should always try to create a workspace and if it exists, the API should throws an error.

**Comment by tamorim** [comment]
#### Para obter uma lista de Workspaces:
`http://api.beta.vtex.com/<account>/workspaces`

> Para criar é a mesma rota, só que um POST

#### Headers:
```
ACCEPT application/vnd.vtex.gallery.v0+json
AUTHORIZATION token <token>
```

#### Para criação, o body da request tem que ser:
```json
{ "name": "sb_<developer_email>" }
```

**Comment by brenoc** [comment]
What happens if it sends a POST with a sandbox that is already created? @amoreira

**Comment by tamorim** [comment]
@brenoc It doesn't give an error, but returns a message warning that the workspace it's already created.
