### ISSUE TITLE
vtex init with store-theme downloads an outdated version

### ISSUE THREAD

**Issue by joaomarcosgris** [vtex/toolbelt#653]
## Expected Behavior

When performing `vtex init` and selecting the store-theme template it should download the most recent version
## Current Behavior

Downloading 0.1.0

**Comment by juliomoreira** [comment]
Hi @joaomarcosgris I believe it's working as expected.

What happens is that `vtex init` generates a new `manifest.json` and fixes a new version number as you can see [here](https://github.com/vtex/toolbelt/blob/a2b997c7d07eb4d8d722023b53dbef1473b3fcad/src/modules/init/index.ts#L155-L168)

**Comment by joaomarcosgris** [comment]
Hey @juliomoreira really appreciate the response. Thanks a lot. Indeed it is working as expected.
