### ISSUE TITLE
Make update notification better

### ISSUE THREAD

**Issue by klzns** [vtex/toolbelt#677]
Currently our update notification does not provide a link to our changelog (and I **always** read it).

npm does provide a link and uses the same package as we do. So we just need to update our code and do link npm does.

## Expected Behavior
Do like npm does:
![image](https://user-images.githubusercontent.com/284515/70911822-72185c80-1ff1-11ea-9769-7dbb77cd7f2a.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/284515/70911899-93794880-1ff1-11ea-97e0-34c5d863eadd.png)

## Possible Solution
The code from npm:
https://github.com/npm/cli/blob/897537ab08261fe4323b0d079047507dba62bc11/bin/npm-cli.js#L85-L130

## Your Environment

* Version used: v2.79.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): v12.8.0
* Operating System and version (desktop or mobile): MacOS
* Link to your project: n/a

**Comment by tiagonapoli** [comment]
Should we list all changelogs from version A to B or just the latest?

**Comment by AlexxNicastro** [comment]
@tiagonapoli Wouldn't it be redundant to list the two, since you'll already get the latest changelog at each update?

Besides, you'll only want to read the changelog of what you're about to update, and not the one becoming outdated, IMO.

**Comment by AlexxNica** [comment]
@tiagonapoli  Wouldn't it be redundant to list the two, since you'll already get the latest changelog at each update?

Besides, you'll only want to read the changelog of what you're about to update, and not the one becoming outdated, IMO.

**Comment by AlexxNica** [comment]
@tiagonapoli Wouldn't it be redundant to list both, since you'll already get the latest changelog at each update?

Besides, you'll only want to read the changelog of what you're about to update, and not the one becoming outdated, IMO.

**Comment by tiagonapoli** [comment]
Oh yes, you're perfectly right
