### ISSUE TITLE
Provide a way to skip user prompts on 'vtex publish'

### ISSUE THREAD

**Issue by tiagonapoli** [vtex/toolbelt#713]
Today, when publishing a new version with `vtex publish` some confirmation questions are asked, in order to avoid the developer to publish something wrong by mistake. Aside of that, temporarily there's an announcement of a new publish process: 

![Screenshot from 2020-01-17 09-52-42](https://user-images.githubusercontent.com/26463288/72613711-223df580-390f-11ea-8b73-3dcf5f363971.png)

This blocks the use of `vtex publish` on scripts. Providing a way to skip these prompts would solve this.

**Comment by tiagonapoli** [comment]
A viable would be using a flag: `--unsafe` or `--yes`, but which one to use?

**Comment by gustavorosolem** [comment]
--force is already used for something else?

**Comment by tiagonapoli** [comment]
Yes, it is, but I think no one uses this option:
```
{
  description: 'Publish app without checking if the sem ver is being respected',
  long: 'force',
  short: 'f',
  type: 'boolean',
},
```

**Comment by luciannojunior** [comment]
`--unsafe` is already used for ignoring Typescript errors, right?

I think we should gather all "force" options and check if they are semantically concise. Maybe replacing some of them with `--force`, that is more common on CLI's...

**Comment by ericreis** [comment]
`-y` and `—yes` seems to be good to automatically confirm all the questions, just like `apt/yum install -y`.

However, if any question needs a negative answer (seems odd to me) it wouldn’t make sense.

**Comment by tiagonapoli** [comment]
IMO `-y, --yes` is the way to go in this case, inspired in other CLIs

**Comment by NataliaGodot** [comment]
> Yes, it is, but I think no one uses this option:
> 
> ```
> {
>   description: 'Publish app without checking if the sem ver is being respected',
>   long: 'force',
>   short: 'f',
>   type: 'boolean',
> },
> ```

Actually this option is used everytime you need to publish a version that violates sem ver conditions (nowadays only applied for node apps, like if you want to change a route path), so it is important for us to keep it.

**Comment by augustolazaro** [comment]
There are some use cases to publish an app with `--force`, like when we remove a route from the app, but it's not a breaking change at all. IMO `--unsafe`/`-u` would be also a good name to this situation, then we can use `--force` to skip all prompt messages.

**Comment by tiagonapoli** [comment]
I think maybe `--unsafe` could get confused with `vtex link --unsafe`, in which Typescript errors would be ignored.

Maybe `--yes` is the way to go:

Yarn example:
https://yarnpkg.com/lang/pt-br/docs/cli/init/#toc-yarn-init-yes-y

Linux has a built-in command to answer `yes` infinitely:
https://unix.stackexchange.com/questions/102484/what-is-the-point-of-the-yes-command

Apt uses `--yes` as well:
https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install

Heroku cli has an example too:
https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-keys-add-key

**Comment by tiagonapoli** [comment]
Then `vtex publish --yes` would answer yes to all confirmation questions, but the command would fail if the user is publishing in an account different than the app vendor - Since `--yes` would be used in scripts seems ok to demand that `vendor === account`, since that's a prerequisite and nowadays there's no automatic way to login to another account

**Comment by tiagonapoli** [comment]
https://github.com/vtex/toolbelt/pull/714
