### ISSUE TITLE
Toolbelt Login doesn't work on Windows+WSL

### ISSUE THREAD

**Issue by luciansr** [vtex/toolbelt#745]
Since the day of the creation of this issue, the `vtex toolbelt` login stopped working on my machine when using `WSL`

Whenever I try to login/link/etc I am redirected to the link: 
`https://{{account}}.myvtex.com/_v/private/auth-server/v1/login/?workspace=master` (without de return URL parameter)
After that, the default store page opens for me, and nothing happens in the CLI 

PS: using the default windows shell/terminal it works fine 😢

![image](https://user-images.githubusercontent.com/1542722/74555179-ed3ab800-4f39-11ea-9d25-a0e44f22a18e.png)

https://vtex.slack.com/archives/C2WSEU9QQ/p1581693375388500

## Possible Solution
Open a login URL with the returnUrl parameter (?)

## Steps to Reproduce (for bugs)

1. On Windows WSL, execute `vtex login` and wait
2. Follow the default steps
3. Login doesn't work 😭

## Your Environment

```
vtex toolbelt: 6.13.4
Updated Windows 10
"Default" Dell XPS 2018 from VTEX
Windows Subsystem for Linux
```

**Comment by tiagonapoli** [comment]
I investigated and discovered that an update to one library was the issue. I already opened an issue in the lib https://github.com/sindresorhus/open/issues/170 and for now you can use an older version of toolbelt - `vtex@2.87.4`. Using `yarn` you can install it with the command:
```
yarn global add vtex@2.87.4
```

**Comment by luciansr** [comment]
It worked @tiagonapoli ! 
Thanks

**Comment by tiagonapoli** [comment]
A patch https://github.com/sindresorhus/open/pull/171 was released by open fixing this issue, this can now be closed - next toolbelt installs will get the latest `open` package with the fix.
