### ISSUE TITLE
Toolbelt fails silently

### ISSUE THREAD

**Issue by dfosco** [vtex/toolbelt#75]
Trying to upload my workspace no longer works since the last time I tried it — a couple of hours ago.

I'm running `storefront-theme` with `vtex watch -s` at branch `prototype/sku-selector-editor`. 
I also have `storefront-editor` and `storefront-sdk` running `vtex watch -w`, both on `master`.

I already checked the cookie, checked my connection, logged out of the toolbelt, opened my browser in an incognito window and re-authenticated with VTEX ID.

Completely silent error :grin:

**Comment by tamorim** [comment]
Did you upgrade it to version *0.12.0*?

**Comment by dfosco** [comment]
Yep! It was a bizarre error, I'll try again now and see if it works — hopefully I'll close this issue :P

**Comment by tamorim** [comment]
I'll close since it wasn't toobelt's fault.

**Comment by dfosco** [comment]
:ok_hand:
