### ISSUE TITLE
Error linking theme

### ISSUE THREAD

**Issue by cristhian-moreno** [vtex/toolbelt#753]
I get an error when giving vtex link in the folder that contains the previously downloaded theme.
![Captura de pantalla de 2020-02-19 15-38-34](https://user-images.githubusercontent.com/51449644/74876356-83ebe800-5331-11ea-9054-c66ca3a64351.png)

**Comment by tiagonapoli** [comment]
This errors persists?
I'm working on a better error handling for toolbelt, as well as better visibility for us - This PR https://github.com/vtex/toolbelt/pull/755 shall improve the situation
