### ISSUE TITLE
Fails repeatedly if there is no package.json on node folder

### ISSUE THREAD

**Issue by lucis** [vtex/toolbelt#758]
When declaring a `node` builder and not including a `package.json` file on the folder, the `vtex link` process fails repeatedly, apparently always resending the files until you kill it.

![image](https://user-images.githubusercontent.com/18706156/75471496-1bc08600-5971-11ea-869b-65c898e5233e.png)

**Comment by NataliaGodot** [comment]
@lucis Please confirm if this bug was resolved.

**Comment by lucis** [comment]
Yes, it was!

Thank you, @NataliaGodot 😄
