### ISSUE TITLE
Failed to run yarn in react

### ISSUE THREAD

**Issue by yessicapire** [vtex/toolbelt#768]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by tiagonapoli** [comment]
Could you give more info on the problem? A screenshot maybe?

**Comment by yessicapire** [comment]
hi, yes of course, I never had trouble running vtex link but, I'm doing new practices and this comes up.
![Captura de Pantalla 2020-03-04 a la(s) 14 52 19](https://user-images.githubusercontent.com/16107276/75908401-d694cc00-5e28-11ea-9b60-aba3a65a7b94.png)

**Comment by yessicapire** [comment]
I don't know if I have to create the whole process again.

**Comment by yessicapire** [comment]
I could not replicate the error, but I updated the entire directory and the link works.
