### ISSUE TITLE
Update login message 

### ISSUE THREAD

**Issue by bellacorbo** [vtex/toolbelt#79]
The message still indicates that the user password is the VTEX registered password. Need to adapt to the new authentication method. 
 
![toolbelt](https://cloud.githubusercontent.com/assets/13241914/11194734/eba7eeb6-8c94-11e5-9b3e-0c60058fe6db.png)

**Comment by brenoc** [comment]
@bellacorbo the email token is only for @vtex.com.br emails, not for the general user.
