### ISSUE TITLE
Rodar dois watchs ao mesmo tempo

### ISSUE THREAD

**Issue by leandrooriente** [vtex/toolbelt#8]
Ao tentar rodar dois watchs ao mesmo tempo o toolbelt da pau. Provavelmente porque tenta rodar sempre na mesma porta.

O ideal seria fazer um random sempre dentro de um range bom 35000/38000 por exemplo.

![screen shot 2015-04-08 at 6 09 25 pm](https://cloud.githubusercontent.com/assets/1781007/7055519/6e8cc448-de1a-11e4-8c60-94df883118da.png)

**Comment by firstdoit** [comment]
Acredito que a melhor solução é outra.

Ao iniciar o livereload, tem que ter um try/catch. Se o servidor não conseguir iniciar com o erro de EADDRINUSE, simplesmente não criamos o servidor mas continuamos mandando os POST's de changed files para localhost na mesma porta.

A lógica é: o primeiro a rodar sobe o servidor. Os demais, percebem que já existe um e simplesmente comunicam que mudaram arquivos.
