### ISSUE TITLE
Unhandled exception when running unlinking an app

### ISSUE THREAD

**Issue by ericreis** [vtex/toolbelt#804]
## Expected Behavior

Successfully unlink the requested app.

## Current Behavior

```
19:37:14.830 - error: Unhandled exception
19:37:14.831 - error: Please report the issue in https://github.com/vtex/toolbelt/issues
19:37:14.831 - error: get https://platform.io.vtex.com/pricingqa/eric
19:37:14.837 - error: ErrorID: fa8a09c4a28f5345
```

## Steps to Reproduce (for bugs)

1. Run `vtex-unlink` in the `admin-promotions` app.

## Your Environment

* Version used: 2.95.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v12.6.0
* Operating System and version (desktop or mobile): MacOS Mojave v10.14.6
* Link to your project: https://github.com/vtex/admin-promotions

**Comment by tiagonapoli** [comment]
Please, try to run with `--verbose` to get more details of the error

**Comment by tiagonapoli** [comment]
Closing due to no follow up
