### ISSUE TITLE
500 Error linking

### ISSUE THREAD

**Issue by wender** [vtex/toolbelt#833]
This morning I updated the toolbelt, then it stops recognising `vtex` command, I updated my *npm* and my *yarn*, uninstalled vtex and installed again.
When I run `vtex link` it throws an error

## Expected Behavior

Last night it was working fine

## Current Behavior

![image](https://user-images.githubusercontent.com/24723/80108048-40407500-8552-11ea-997d-84ea9b34ff9d.png)

## Steps to Reproduce (for bugs)

1. Update vtex toolbelt
2. Update npm
3. Update yarn
4. Uninstall vtex toolbelt
5. Install vtex toolbelt
4. run `vtex link`

## Your Environment

* Version used: vtex/2.98.0 
* Environment name and version (e.g. Chrome 39, node.js 5.4): node-v12.13.1
* Operating System and version (desktop or mobile): OSX 10.15.4 (19E287)
* Link to your project: http://wender--sandboxusdev.myvtex.com/

**Comment by tiagonapoli** [comment]
It appears to be a partial outage on npm registry, which is not ours to solve, but I think this is temporary.

Is it still failing?

**Comment by trmasaki** [comment]
I had, the exactly same problem, some minutes ago.  But now it seems to be solved.

**Comment by wender** [comment]
It's linking again even with an error `An unexpected error occurred: "https://github.com/vtex/node-stats-lite: ESOCKETTIMEDOUT".` I'll close the issue
