### ISSUE TITLE
Problem vtex link

### ISSUE THREAD

**Issue by yaneth94** [vtex/toolbelt#871]
When I run vtex link in store-theme it gives me this problem
![image](https://user-images.githubusercontent.com/21286767/83064563-301f2800-a01f-11ea-9c37-a615aef8928d.png)
[](url)

**Comment by tiagonapoli** [comment]
Hi, I searched the ErrorID that was shown and it appeared to be a temporary network issue on you computer - the problem persists?

**Comment by yaneth94** [comment]
Well it seems strange to me, because just with the store-theme I get https://github.com/vtex-apps/store-theme, when I create a project from scratch by the vtex init command line I have not had a problem, it is that I need to use some things from that topic, could you help me please
![image](https://user-images.githubusercontent.com/21286767/83073864-631ce800-a02e-11ea-8353-8105efa3317a.png)

**Comment by tiagonapoli** [comment]
Hmm, it seems it's because of the project size - you're sending 2.11MB to our platform, if your internet upload is not that good the connection may timeout

**Comment by yaneth94** [comment]
I doubt it, i have a good bandwidth

**Comment by tiagonapoli** [comment]
Just to test out try removing the `public` folder, which has 2mb, and link

**Comment by yaneth94** [comment]
many thanks :smiley:
