### ISSUE TITLE
Include 'vtex admin' command

### ISSUE THREAD

**Issue by crisvtex** [vtex/toolbelt#888]
## Expected Behavior
It would be great to have a 'vtex admin' command, that would open a browser window showing admin home for the account on which we are logged in.

## Current Behavior
Toolbelt does not provide such option.

## Possible Solution
Similar to 'vtex browse' but instead of going to "/" it goes to "/admin".

## Context
Day to day we use more toolbelt, and it will save some time in development and support, if not more areas.

**Comment by tiagonapoli** [comment]
I don't know if it would be good enough, but if you run `vtex browse admin` it'll open the admin

**Comment by tiagonapoli** [comment]
You can run `vtex browse path/to/something` and it will open `/path/to/something` on your workspace/account 
```
Open endpoint in browser window

USAGE
  $ vtex browse [PATH]

OPTIONS
  -h, --help     show CLI help
  -q, --qr       Outputs a QR Code on the terminal
  -v, --verbose  Show debug level logs
  --trace        Ensure all requests to VTEX IO are traced

EXAMPLES
  vtex browse
  vtex browse admin
```

**Comment by crisvtex** [comment]
Thank @tiagonapoli that would suffice. Thread closed :)
