### ISSUE TITLE
Run NPM install if user forgot it.

### ISSUE THREAD

**Issue by leandrooriente** [vtex/toolbelt#89]

**Comment by brenoc** [comment]
We show this message:
> 'Did you install ' + pkgName + '?'

[Source](https://github.com/vtex/toolbelt/blob/03880b3ebd5886f42cc1d7b04b837a8c1712e57c/src/lib/webpack.js#L17)

Do you think is good enough?

**Comment by firstdoit** [comment]
This should be part of the new `vtex init` command.
