### ISSUE TITLE
Crash ao tentar publicar uma versão já publicada

### ISSUE THREAD

**Issue by leandrooriente** [vtex/toolbelt#9]
Ao tentar dar um publish numa versão que já foi publicada a CLI explode.

![screen shot 2015-04-08 at 6 19 37 pm](https://cloud.githubusercontent.com/assets/1781007/7055714/0d458b50-de1c-11e4-8d4b-4a7d984fb7c1.png)

**Comment by leandrooriente** [comment]
Não necessariamente já publicada.

**Comment by tamorim** [comment]
@brenoc Ainda continua esse erro?

**Comment by tamorim** [comment]
@brenoc bump

**Comment by brenoc** [comment]
@tamorim vou testar

**Comment by brenoc** [comment]
@tamorim ta falhando bem:

```
Publishing storefront-banner 0.2.0
Compressing files...

 53243 total bytes. Publishing...
Sending files...

Failed to publish app
{ status: 409,
  body: '{"id":111,"code":"AppAlreadyInstalled","message":"This app is already installed","details":null}' }
```

**Comment by brenoc** [comment]
@tamorim talvez pegar a message da mensagem de erro e printar bonita

**Comment by tamorim** [comment]
Acho válido sim!

**Comment by brenoc** [comment]
Vou criar uma outra issue pra isso
