### ISSUE TITLE
Error when trying to run vtex command

### ISSUE THREAD

**Issue by igorpoubel** [vtex/toolbelt#901]
When I execute vtex link or list (the only I tested) I'm having an exception.
It just started to happen.

![image](https://user-images.githubusercontent.com/6241622/87470431-23688a80-c5f3-11ea-9ac6-db41fa19d1ec.png)
a98817fbce28fef631b71e48c9e5b6b6

![image](https://user-images.githubusercontent.com/6241622/87470453-2bc0c580-c5f3-11ea-872d-bdc928fd6ef4.png)
a2d96efb033517af2906742ee107a0d2

**Comment by tiagonapoli** [comment]
I checked and the errors were network timeouts - it can be that the service wasn't available for a short time

**Comment by tiagonapoli** [comment]
Thanks for the report!
