### ISSUE TITLE
How to Change page title

### ISSUE THREAD

**Issue by yaneth94** [vtex/toolbelt#935]
change the title of the page that has the search intelligent implemented (https://help.vtex.com/tracks/vtex-intelligent-search--19wrbB7nEQcmwzDPl1l4Cb/3qgT47zY08biLP3d5os3DG) and currently it puts me undefined.

It only happens when I select a category from the category-menu (https://vtex.io/docs/components/all/vtex.category-menu@2.14.0/) I would like you to help me because I need to fix it, thanks in advance

![image](https://user-images.githubusercontent.com/21286767/90449315-67dcbf80-e0a4-11ea-8d45-70488f6bf393.png)

![image](https://user-images.githubusercontent.com/21286767/90449283-5398c280-e0a4-11ea-9977-6bb86a086e1e.png)

![image](https://user-images.githubusercontent.com/21286767/90449299-5eebee00-e0a4-11ea-83bd-4d3a14172221.png)

**Comment by tiagonapoli** [comment]
Hi! I think the best place for this question would be in this repo: https://github.com/vtex-apps/store-discussion

**Comment by yaneth94** [comment]
thanks
