### ISSUE TITLE
Dont open navigator on login

### ISSUE THREAD

**Issue by wowpato** [vtex/toolbelt#941]
I'm experienceing an issue to login. Is just hangs after specifing the account:

My current OS is "Linux version 5.4.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020"

I reviewed the login code here: https://github.com/vtex/toolbelt/blob/60bb7edd56474920dd25ac41bf9e9cd9ddc62e5b/src/lib/auth/AuthProviders/OAuthAuthenticator/LoginServer.ts
but couldn't find a way to generate the link manually for the login.

Kind Regards,

**Comment by tiagonapoli** [comment]
Can you try to clone and run this project? https://github.com/tiagonapoli/toolbelt-login-test
To run you just have to install the dependencies:
```
yarn
```
And run:
```
yarn start
```
This is a minimal example of the login, you can change the account here: https://github.com/tiagonapoli/toolbelt-login-test/blob/541d886f0c0fa2ec3424f3e1cfa38c01d6b31d38/src/app.js#L11

All the requests made are available on this file: https://github.com/tiagonapoli/toolbelt-login-test/blob/master/src/vtexid.js

**Comment by tiagonapoli** [comment]
If you wait for like 15s does an error appears? It may be a firewall issue causing a timeout - does your company have some kind of proxy or firewall?
