### ISSUE TITLE
Error signing in to another vtex account

### ISSUE THREAD

**Issue by lucalves** [vtex/toolbelt#956]
## Expected Behavior
Being able to log in to a different vtex account.

## Current Behavior
Generating the following error:

![error-appliancetheme](https://user-images.githubusercontent.com/17712401/94147956-642f1c00-fe4c-11ea-866c-8b4f71939b98.png)

With ErrorID: `c9310bdf9a48a0770ec6724f6ccd3a6b`

## Your Environment

* Version used: vtex/2.111.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Using node.js v12.16.2
* Operating System and version (desktop or mobile): Windows 10 x64

**Comment by thiagotlcs** [comment]
I had the same problem when trying to login, and when trying again after a few hours it worked normally.

I had to redo the vtex installation
