### ISSUE TITLE
Error al lanzar el comando vtex link

### ISSUE THREAD

**Issue by acostacarlosf1995** [vtex/toolbelt#971]
Desde que actualice a la nueva version de vtex, estoy teniendo problemas con el comando `vtex link` y basicamente me lanza error con todas las tiendas en las que trato de entrar

hay alguna forma de volver a la version anterior?

**Comment by mroffe** [comment]
Intentá desintalar y volver a instalar Yarn
npm uninstall -g yarn
yarn global add vtex
