### ISSUE TITLE
Error when running vtex link command

### ISSUE THREAD

**Issue by gabriellycastro** [vtex/toolbelt#972]
## Expected Behavior
Start a development session for the application

## Current Behavior
$ error: Unhandled exception
$ error: Please report the issue in https://github.com/vtex/toolbelt/issues
$ error: post https://app.io.vtex.com/vtex.builder-hub/v0/cybelar/feature21539001/_v/builder/0/link/cybelar.store-theme@0.17.14
$ error: ErrorID: b5cda793df173126d595df82b9b68dec

## Your Environment
vtex/2.115.3 win32-x64 node-v10.16.3

**Comment by despossivel** [comment]
I have the same problem, could you find a solution for this?

**Comment by gabriellycastro** [comment]
Hi @despossivel.

So far there are two things that worked for other developers with the same problem.
It haven't worked for me, but you can try and see if it does for you

1° thing: updating node and then toolbelt and booting
2° thing: deleting yarn and installing "yarn global add vtex@2.110.2-beta.0" and booting

**Comment by VerasThiago** [comment]
Hi guys, did you tried to update `toolbelt` ? Running `yarn global add vtex` the current version is `2.118.1` maybe can solve the problem. Second, can you explain the workflow that you did to get this error ?

**Comment by despossivel** [comment]
@gabriellycastro @VerasThiago a piece of my squad found a way to solve this problem: unlinking all apps in the workspace

and things went well

**Comment by despossivel** [comment]
@VerasThiago the problem happens to me right after upgrading to that version
