### ISSUE TITLE
Vtex link not working

### ISSUE THREAD

**Issue by despossivel** [vtex/toolbelt#996]
When I try to run a vtex link, everything starts to go well, but get to a certain% and start from 0% again and report the error

13: 53: 13,872 - error: Error receiving the zip file of the vtex.builder-hub@0.270.2 project

does anyone know tell me something about?

**Comment by klzns** [comment]
Can you provide the vendor, name and version of the app, please?

**Comment by despossivel** [comment]
@klzns shoulder@1.0.2

**Comment by klzns** [comment]
@despossivel which vendor?

**Comment by despossivel** [comment]
@klzns shoulder

**Comment by klzns** [comment]
@despossivel it's shoulder.shoulder@1.0.2 then?

**Comment by despossivel** [comment]
@klzns yes!
